version: "2"
services:
    app:
        build:
            args:
                - DEBUG=0
        restart: always
        environment:
           - DEBUG=0
    worker_classify:
        restart: always
    rabbitmq:
        restart: always
