version: "2"
services:
    app:
        build:
            context: ./
            dockerfile: build/app/Dockerfile
        ports:
            - "8000:8000"
        networks:
            - ojah_net
        volumes:
            - ./:/ojah
        depends_on: [rabbitmq]
    worker_classify:
        build:
            context: ./
            dockerfile: build/worker_classify/Dockerfile
        networks:
            - ojah_net
        volumes:
            - ./:/ojah
        depends_on: [rabbitmq]
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
        networks:
            - ojah_net
networks:
    ojah_net:
        driver: "bridge"
